# Generated by Django 3.1.2 on 2020-10-27 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Состояние-оформляется не оформляется')),
                ('time', models.DateTimeField(verbose_name='Время резервации')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket', to='item.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket', to='user.tmsuser')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзинаы',
                'db_table': 'ucket',
            },
        ),
    ]
