# Generated by Django 3.1.3 on 2020-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='geeks_field',
            field=models.BooleanField(default=True),
        ),
    ]
